FROM arm64v8/alpine:3.12 as alpine
RUN apk add -U --no-cache ca-certificates


FROM arm64v8/alpine:3.12

ENV GODEBUG netdns=go
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ADD release/linux/arm64/plugin /bin/
ENTRYPOINT ["/bin/plugin"]