# escape=`

FROM mcr.microsoft.com/windows/servercore:1809
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
USER ContainerAdministrator

ENV GODEBUG=netdns=go
RUN mkdir /bin
ADD release/windows/amd64/plugin C:/bin/plugin.exe

ENTRYPOINT [ "C:\\bin\\plugin.exe" ]